### ISSUE TITLE
Extract rifui library

### ISSUE THREAD

**Issue by vojtechsimetka** [rsksmart/rif-communications-chat#43]
## Rationale
The`rifui` folder in `/src` is intended to collect all UI components that could be useful for other services using the RIF UI.  It should be extracted into external library and published as package [npmjs.com](https://npmjs.com).

## Tasks
- [ ] extracting the library into new github repo
- [ ] publishing the library on npmjs
- [ ] removing the `/src/rifui` folder
- [ ] removing the reference in `tslint.conf`
- [ ] adding dependency to package.json
